version: '2'
services:
  db:
    image: mysql:8.0.19
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - ./mysql-confd:/etc/mysql/conf.d
    ports:
      - "4306:3306"

  app:
    tty: true
    stdin_open: true
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myworkspace
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db

volumes:
  mysql-data:
  bundle:    